const fs=require('fs');const path=require('path');
const BASE='https://raw.githubusercontent.com/Ephellon/game-store-catalog/master/xbox/';
const letters=['!','_','$',...'abcdefghijklmnopqrstuvwxyz'];
const MARKET='CA',LANG='en-CA';
async function get(url){const r=await fetch(url,{headers:{'User-Agent':'GameDB-XboxDB/1.0'}});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json()}
function num(v){const n=Number(String(v??'').replace(/[^0-9.]/g,''));return Number.isFinite(n)?n:0}
function arr(v){if(Array.isArray(v))return v.flatMap(x=>typeof x==='string'?[x]:x&&typeof x==='object'?[x.Name,x.name,x.Title,x.title].filter(Boolean):[]).filter(Boolean);if(typeof v==='string')return v.split(/[,|]/).map(x=>x.trim()).filter(Boolean);return []}
function extractCategories(p){const out=[];const walk=o=>{if(!o||typeof o!=='object')return;if(Array.isArray(o)){o.forEach(walk);return}for(const k of ['Categories','categories']){if(Array.isArray(o[k]))for(const c of o[k]){const n=typeof c==='string'?c:c?.Name||c?.name||c?.Title||c?.title;if(n)out.push(n)}}Object.values(o).forEach(v=>{if(v&&typeof v==='object')walk(v)})};walk(p);return [...new Set(out.map(String).map(x=>x.trim()).filter(x=>x&&x.toLowerCase()!=='games'&&x.toLowerCase()!=='apps'))]}
async function details(ids){const out=new Map();for(let i=0;i<ids.length;i+=50){const batch=ids.slice(i,i+50);try{const u=new URL('https://displaycatalog.mp.microsoft.com/v7.0/products');u.searchParams.set('actionFilter','Browse');u.searchParams.set('bigIds',batch.join(','));u.searchParams.set('fieldsTemplate','Details');u.searchParams.set('market',MARKET);u.searchParams.set('languages',LANG);const d=await get(u);for(const p of d.Products||[]){const id=String(p.ProductId||p.productId||'');if(!id)continue;const lp=(p.LocalizedProperties||[])[0]||{};const cats=extractCategories(p);out.set(id,{description:lp.ProductDescription||lp.ProductDescriptionShort||'',shortDescription:lp.ProductDescriptionShort||'',developer:lp.DeveloperName||lp.PublisherName||'',publisher:lp.PublisherName||'',genres:cats,releaseDate:(p.MarketProperties||[])[0]?.OriginalReleaseDate||'',storeUrl:lp.ProductUrl||''})}}catch(e){console.log(`detail batch ${i}: ${e.message}`)}}return out}
async function main(){let raw=[];for(const l of letters){try{const d=await get(BASE+encodeURIComponent(l)+'.json');if(Array.isArray(d))raw.push(...d)}catch(e){console.log('skip',l,e.message)}}const map=new Map();for(const x of raw){if(!x||!x.name)continue;const type=String(x.type||'').toLowerCase();if(type&&type!=='product'&&type!=='game')continue;const id=String(x.uuid||x.href||x.name);if(!map.has(id))map.set(id,{id,title:x.name,price:num(x.price),currency:'CAD',image:x.image||'',href:x.href||'',platforms:arr(x.platforms),genres:[],description:'',shortDescription:'',developer:'',publisher:'',releaseDate:'',rating:x.rating||''})}const games=[...map.values()];if(games.length<1000)throw new Error(`Safety check failed: only ${games.length} Xbox games`);const ds=await details(games.map(g=>g.id));for(const g of games){const d=ds.get(g.id);if(!d)continue;Object.assign(g,d);if(!g.genres.length)g.genres=d.genres||[];if(d.storeUrl)g.href=d.storeUrl}games.sort((a,b)=>a.title.localeCompare(b.title));fs.writeFileSync(path.join(process.cwd(),'xbox','games.json'),JSON.stringify(games));console.log(`Prepared ${games.length} Xbox games; enriched ${ds.size}`)}main().catch(e=>{console.error(e);process.exit(1)})